### ISSUE TITLE
주기적 리랜더링

### ISSUE THREAD

**Issue by FoocoJun** [FoocoJun/React_practice#1]
[**simhwa 리포지토리**](https://github.com/FoocoJun/React_practice/tree/main/simhwal)

### 문제
> 사용자A가 게시글을 작성하면 리덕스 스토어에 업로드가 되므로 리랜더가 됩니다.
하지만 타인B가 작성시 직접적으로 웹의 버튼을 누른게 아니기 때문에 
데이터베이스의 내용은 바뀌지만 사용자A의 리덕스 스토어가 바뀌지 않게 됩니다.
그러므로 사용자 A는 새로고침을 하지 않는 이상 업데이트가 되지 않습니다.

### 접근법
> `데이터베이스의 값이 바뀌면` 자동으로 app.js 혹은 하위 컴포넌트가 `리랜더`가 되기를 바라는데 
그 방식으로 떠오른 것은 주기적인 리랜더링이었습니다.

### 엥?
> `setIterval`과 `setTimeout`을 사용해 찍먹을 해봤지만 리랜더가 무한 반복된다고 리엑트가 막았습니다.
`Too many re-renders. React limits the number of renders to prevent an infinite loop.`

### 시간부족으로 포기 (22-7-21 21시 땡)
> 댓글을 작성하면 실시간으로 뿅뿅 올라오는 기능을 구현해보고 싶습니다.
코드에 대한 질문보단
일반적으로 사용되는 방법이 있는지 알고싶습니다.

**Comment by cslim0527** [comment]
**Q&A**
Q. 다른사람이 댓글과 게시글을 작성시 새로고침을 눌러야 업데이트가 됩니다.

A. 실시간 서비스 처럼 다른 사용자의 인터랙션을 감지하는 방법에 대해 고민중이시군요!
나아가서 setInterval, setTimeout까지 생각해서 시도해보셨다니 너무 좋은 접근법 인것 같습니다.

[첫번째 방법]
interval을 구현한 방식이 잘못되어 무한 리렌더에 빠지지 않았나 생각됩니다.
아래와 같은 방법으로 클라이언트에서 주기적으로 요청하는 폴링 방식을 사용하여 지속적으로 새 정보를 요청한다면 구현하고자 하는 방향으로
기능 구현이 될것같습니다. 다만 interval 을 사용할 때 컴포넌트가 unmount 될때 해당 interval을 clear 할 수 있도록
useEffect의 cleanup 함수에서 꼭 로직을 작성해주어야합니다.


```javascript
// PostDetail.js 
  React.useEffect(() => {
      const intervalId = setInterval(() => {
          KeepPostData()
      }, 3000)

      return () => {
          clearTimeout(intervalId)
      }
  }, []);
```

이런 방법으로도 해결이 가능해보이지만 값이 변하지 않았는데도 지속적으로 API를 호출한다면 불필요한 비용이 발생 할 수도 있다는 점에서
다른방법을 모색해볼 수 있을것 같습니다.

[두번째 방법]

그렇다면 댓글을 작성하는 작성자 시점에서 가능한한 최신의 데이터를 보여주는 방식을 고민해 볼 수 있을것 같은데요👀
댓글 작성 시 작성자의 댓글만 렌더링하는것이 아니라 포스팅 데이터 전체 (또는 댓글 정보만) API로 요청해 가장 최근의 댓글까지 함께 렌더링 할 수있도록 하는 방법도 가능 할 것 같습니다.

[세번째 방법]

말씀하신 모든 내용은 사실 <채팅> 기능을 생각해보면 거의 같다고 할 수 있습니다.
클라이언트에서 서버로 데이터를 요청하지않아도 서버의 데이터 변동이 일어났을때 클라이언트로 데이터를 보낼 수 있도록 "양방향 통신" 을
지원해야 합니다. 채팅은 이런 양방향 통신을 사용하기 때문에 내가 채팅을 보내고있지 않아도 상대방이 보낸 메시지를 실시간으로 보게 됩니다.

프론트엔트 개발에서 이런 채팅 서비스를 구현하기위해서 socket 이란 개념을 공부합니다.
socket은 양방향 통신을 지원하여 위와 같은 환경을 구성할수 있도록 합니다.

**전체리뷰**

전체적으로 개발하신 프로덕션이 굉장히 디테일이 높고 심미적으로도 완성도가 높아 정말 칭찬드리고 싶습니다.
반응형 스타일링까지 적용하시다니 능력자시네요👍👍

간단한 사용 테스트 시 발견한 버그로 새로고침 시 로그인 풀리는 현상이 있어 이 부분은 빠르게 픽스해보시는게 도움이 될 것 같습니다.

또 사용자가 라우팅이 정의되어있지 않은 경로로 접근했을때 404 페이지를 만들어 접근 할 수 없는 페이지임을 알려주는것도 좋을것 같습니다.
예를들어 아래와 같은 경로로 접근 시 현재 빈화면만 노출되어 사용자 입장에서는 사이트가 멈춘것인지 로딩중인것인지 헷갈릴 수도 있을것 같아요.
http://sparta-mv.shop.s3-website.ap-northeast-2.amazonaws.com/test

그리고 FeedLayout0 ~ 2 컴포넌트의 경우 레이아웃이 다르기때문에 컴포넌트를 나눈것으로 보이는데,
같은 데이터를 사용하시고 있기때문에 하나의 컴포넌트로 관리하여 코드를 관리하면 유지보수면에서 더 나은 퍼포먼스를 도출 할 수 있을것 같습니다.

예시 코드를 아래 첨부해드릴게요.
```javascript
<FeedLayout type="left" data={data} />
<FeedLayout type="right" data={data} />
<FeedLayout type="top" data={data} />
```


**끝으로**
앞으로 굉장히 발전가능성이 무궁무진하고 개발하실때 구현하고자 하는 기능에 대해서 접근하시는 방식이 진짜 개발자스러우시네요!
짧은 기간인데 불구하고 높은 완성도를 보여주신것같습니다.
너무 고생많으셨습니다!
